# my_kitty config with themes
#-------------------------------------------------------------------
font_size                   13.0
window_margin_width			10
background_opacity			0.8
map ctrl+shift+c			copy_to_clipboard
map ctrl+shift+v			paste_from_clipboard
mouse_map ctrl+right click	grabbed,ungrabbed 	paste_from_clipboard
mouse_map ctrl+left click	grabbed,ungrabbed 	copy_to_clipboard
initial_window_width		900
initial_window_height		500
remember_window_size		no
shell						/usr/bin/fish
# Tab bar config
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         round
tab_title_max_length        27
tab_title_template          "[{index}] {title[title.rfind('/')+1:]}"
active_tab_title_template   "[{index}] {title[title.rfind('/')+1:]}"
active_tab_font_style       bold
tab_bar_background          #444
inactive_tab_background     #999
inactive_tab_foreground     #444
active_tab_background       #73D216
active_tab_foreground       #000
#-------------------------------------------------------------------

# BEGIN_KITTY_THEME
# Wombat
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='Source Code Pro' postscript_name=SourceCodePro-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
