[files]
current_page=0
recent_files=/home/as/.themes/Avokado/openbox-3/themerc;/home/as/.config/openbox/autostart;/home/as/.config/qt6ct/qt6ct.conf;/home/as/.config/qt5ct/qt5ct.conf;/home/as/.config/openbox/environment;/home/as/.config/tint2/gruvbox.left.tint2rc;/home/as/.config/tint2/gruvbox.bottom.tint2rc;/home/as/.config/tint2/groove.left.tint2rc;/home/as/.config/tint2/groove.bottom.tint2rc;/home/as/.config/tint2/fleon.left.tint2rc;
recent_projects=
FILE_NAME_0=0;Conf;0;EUTF-8;0;1;1;%2Fhome%2Fas%2F.themes%2FAvokado%2Fopenbox-3%2Fthemerc;0;4

[project]
session_file=
project_file_path=/home/as/проекты

[geany]
treeview_position=156
msgwindow_position=368
geometry=70;8;900;600;0;
sidebar_page=1

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
